### ISSUE TITLE
Get freebox mini 4k code

### ISSUE THREAD

**Issue by ChoiZ** [Desaydrone/snips-app-TelecommandeFreebox#4]
Hello, I try to get the code from my freebox mini 4k I don't know how to get it.

My remote is connected via bluetooth and i want to change the channel via curl.

If you have some idea.

Regards,

**Comment by Desaydrone** [comment]
Sorry, the Mini 4K remote doesn't work like the Freebox Revolution, 

For the revolution i use url like 

`http://hd1.freebox.fr/pub/remote_control?code=blue`

But for the mini 4K that doesn't work and free doesn't give somthing to play with to do that. 

Sorry

**Comment by ChoiZ** [comment]
Ok thanks for your answer. 

Regards,
